### ISSUE TITLE
How do I submit a challenge?

### ISSUE THREAD

**Issue by CxlledMax** [MorpheusCodingChallenges/challenge-template#2]
I don't know how to submit a challenge, please help me.

**Comment by Defelo** [comment]
To submit a challenge, please send an email to kontakt@the-morpheus.de.

**Comment by CxlledMax** [comment]
> 
> 
> To submit a challenge, please send an email to [kontakt@the-morpheus.de](mailto:kontakt@the-morpheus.de).

Thanks
